[package]
name = "raft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tarpc = { version = "0.25", features = ["full"] }
tokio = { version = "1", features = ["full"] }
regex = "1"
etcd-rs = "0.3.0"

[features]
server = []
client = []
agent = []